Repository nextcloud/.github, pull requests merged in 2021-07, with the labels that each got.

#13 Various linting scripts
  workflow-templates/lint-eslint.properties.json
  workflow-templates/lint-eslint.svg
  workflow-templates/lint-eslint.yml
  workflow-templates/lint-php-cs.properties.json
  workflow-templates/lint-php-cs.yml
  workflow-templates/lint-php.properties.json
  workflow-templates/lint-php.svg
  workflow-templates/lint-php.yml
  workflow-templates/lint-stylelint.properties.json
  workflow-templates/lint-stylelint.svg
  workflow-templates/lint-stylelint.yml
Labels: 3. to review, enhancement

#7 Add compile command
  workflow-templates/command-compile.properties.json
  workflow-templates/command-compile.svg
  workflow-templates/command-compile.yml
Labels: 2. developing, enhancement

#15 Improve dispatch workflow
  .github/workflows/dispatch-workflow.yml
Labels: 3. to review

#14 Add npm-publish
  workflow-templates/npm-publish.properties.json
  workflow-templates/npm-publish.svg
  workflow-templates/npm-publish.yml
Labels: 3. to review, enhancement

#16 Improve dependabot auto-approve-merge
  workflow-templates/dependabot-approve-merge.yml
Labels: 3. to review
