Repository nextcloud/.github, pull requests merged in 2022-05, with the labels that each got.

#58 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#62 Bump cirrus-actions/rebase to 1.6
  workflow-templates/command-rebase.yml
Labels: 3. to review

#65 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#69 Run PHPUnit workflows on main branch
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-oci.yml
  workflow-templates/phpunit-pgsql.yml
  workflow-templates/phpunit-sqlite.yml
Labels: 3. to review

#71 Add 8.1 to PHP lint matrix
  workflow-templates/lint-php.yml
Labels: 4. to release
