Repository nextcloud/.github, pull requests merged in 2022-01, with the labels that each got.

#33 Add a global CONTRIBUTING.md and SECURITY.md for all orga repos
  CONTRIBUTING.md
  SECURITY.md
Labels: 4. to release

#36 Add a github action to block merges during server freeze
  workflow-templates/block-merge-freeze.json
  workflow-templates/block-merge-freeze.svg
  workflow-templates/block-merge-freeze.yml
Labels: 3. to review

#38 Add filePatterns to workflows
  workflow-templates/dependabot-approve-merge.properties.json
  workflow-templates/lint-eslint.properties.json
  workflow-templates/lint-info-xml.properties.json
  workflow-templates/lint-php-cs.properties.json
  workflow-templates/lint-php.properties.json
  workflow-templates/lint-stylelint.properties.json
  workflow-templates/node.properties.json
  workflow-templates/npm-publish.properties.json
Labels: 3. to review, enhancement

#43 Add `Block merging for EOL` workflow
  workflow-templates/block-merge-eol.properties.json
  workflow-templates/block-merge-eol.svg
  workflow-templates/block-merge-eol.yml
Labels: 3. to review

#44 Drop php 7.3
  workflow-templates/lint-php.yml
Labels: 3. to review
