Repository nextcloud/.github, pull requests merged in 2022-04, with the labels that each got.

#53 Add workflows for phpunit
  workflow-templates/phpunit-mysql.properties.json
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-oci.properties.json
  workflow-templates/phpunit-oci.yml
  workflow-templates/phpunit-pgsql.properties.json
  workflow-templates/phpunit-pgsql.yml
  workflow-templates/phpunit-sqlite.properties.json
  workflow-templates/phpunit-sqlite.yml
  workflow-templates/phpunit.svg
Labels: 3. to review

#54 Do not build with krankerl if no config exists
  workflow-templates/appstore-build-publish.yml
Labels: 3. to review, bug, high

#57 fix permissions for the rebase workflow
  workflow-templates/command-rebase.yml
Labels: 3. to review, bug

#59 Add missing headers in phpunit workflows
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-oci.yml
  workflow-templates/phpunit-pgsql.yml
  workflow-templates/phpunit-sqlite.yml
Labels: 3. to review
