Repository nextcloud/.github, pull requests merged in 2023-04, with the labels that each got.

#134 fix(update-nextcloud-ocp): Fix resetting other dependencies
  workflow-templates/update-nextcloud-ocp-matrix.yml
  workflow-templates/update-nextcloud-ocp.yml
Labels: 3. to review, bug

#137 update block-merge-eol workflow
  workflow-templates/block-merge-eol.yml
Labels: 3. to review

#141 Create npm-audit-fix
  workflow-templates/npm-audit-fix.yml
  workflow-templates/npm-audit-properties.json
  workflow-templates/npm-audit.svg
Labels: 3. to review, enhancement

#142 change npm-audit-fix into a matrix run
  workflow-templates/npm-audit-fix.yml
Labels: 3. to review, bug

#143 update npm-audit-fix 2
  workflow-templates/npm-audit-fix.yml
Labels: 3. to review, bug
