Repository nextcloud/.github, pull requests merged in 2023-06, with the labels that each got.

#169 fix(phpunit): Missing space hurts my eyes
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-oci.yml
Labels: 3. to review

#171 chore(deps): Update xmllint action to use an up to date base image
  workflow-templates/lint-info-xml.yml
Labels: 3. to review

#173 feat: migrate to skjnldsv/block-fixup-merge-action
  .github/workflows/fixup.yml
  workflow-templates/fixup.yml
Labels: 3. to review

#172 chore(deps): Use GHCR images for our database services
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-oci.yml
  workflow-templates/phpunit-pgsql.yml
Labels: 3. to review, bug

#175 fix(documentation): allow to test build if we're not pushing new docs
  workflow-templates/documentation.yml
Labels: 3. to review

#182 fix: Delay mysql configuration so the service has more time to start
  workflow-templates/phpunit-mysql.yml
Labels: 3. to review

#184 chore: remove obsolete command-rebase workflow
  workflow-templates/command-rebase.properties.json
  workflow-templates/command-rebase.svg
  workflow-templates/command-rebase.yml
Labels: 3. to review

#183 feat: cache git repository for faster checkout
  workflow-templates/command-compile.yml
Labels: 3. to review, enhancement, performance

#185 feat: add node testing workflow
  workflow-templates/node-test.properties.json
  workflow-templates/node-test.svg
  workflow-templates/node-test.yml
Labels: 3. to review

#188 feat(npm-publish): Also publish packages on github package registry
  workflow-templates/npm-publish.yml
Labels: 3. to review

#190 feat: add cypress workflow
  workflow-templates/cypress.properties.json
  workflow-templates/cypress.svg
  workflow-templates/cypress.yml
Labels: 3. to review

#191 fix: cypress template
  workflow-templates/cypress.yml
Labels: 3. to review, bug
