Repository nextcloud/.github, pull requests merged in 2023-01, with the labels that each got.

#107 Fix(update-nextcloud-ocp): Fix automatic updates of vendor-bin depend…
  workflow-templates/update-nextcloud-ocp-matrix.yml
  workflow-templates/update-nextcloud-ocp.yml
Labels: 3. to review, bug

#108 chore(CI): Add the GITHUB_TOKEN to setup-php to reduce the rate-limit…
  workflow-templates/appstore-build-publish.yml
  workflow-templates/lint-php-cs.yml
  workflow-templates/lint-php.yml
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-oci.yml
  workflow-templates/phpunit-pgsql.yml
  workflow-templates/phpunit-sqlite.yml
  workflow-templates/psalm-matrix.yml
  workflow-templates/psalm.yml
  workflow-templates/update-nextcloud-ocp-matrix.yml
  workflow-templates/update-nextcloud-ocp.yml
Labels: 3. to review

#109 chore: bump krankerl to 0.14.0
  workflow-templates/appstore-build-publish.yml
Labels: 3. to review

#111 feat: add workflow to pass eslint when no JavaScript was changed
  workflow-templates/lint-eslint-when-unrelated.properties.json
  workflow-templates/lint-eslint-when-unrelated.yml
  workflow-templates/lint-eslint.yml
Labels: 3. to review

#113 feat(eslint): run workflow on changed eslintrc and eslintingore
  workflow-templates/lint-eslint-when-unrelated.yml
  workflow-templates/lint-eslint.yml
Labels: 3. to review, enhancement

#114 Upgrade `fallbackNode` and `fallbackNpm` to Nextcloud supported versions
  workflow-templates/appstore-build-publish.yml
  workflow-templates/command-compile.yml
  workflow-templates/lint-eslint.yml
  workflow-templates/lint-stylelint.yml
  workflow-templates/node.yml
  workflow-templates/npm-publish.yml
Labels: 4. to release

#115 fix(phpunit): Move the phpunit configs to composer
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-oci.yml
  workflow-templates/phpunit-pgsql.yml
  workflow-templates/phpunit-sqlite.yml
Labels: 3. to review

#116 feat(phpunit): Fail the action when unit and integration tests are sk…
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-oci.yml
  workflow-templates/phpunit-pgsql.yml
  workflow-templates/phpunit-sqlite.yml
Labels: 3. to review, enhancement

#118 chore(templates): update command-compile `check-actor-permission` and `parse-command-comment` versions
  workflow-templates/command-compile.yml
Labels: 3. to review

#119 fix(fixup): Add back `synchronize` event type
  workflow-templates/fixup.yml
Labels: 3. to review, bug, regression

#120 fix(phpunit): Align admin credentials
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-pgsql.yml
  workflow-templates/phpunit-sqlite.yml
Labels: 3. to review, bug
