Repository nextcloud/.github, pull requests merged in 2023-05, with the labels that each got.

#146 fix(update-nextcloud-ocp): Fix main branch nextcloud/ocp updates beca…
  workflow-templates/update-nextcloud-ocp.yml
Labels: 3. to review, bug

#147 fix: match naming of npm-audit-fix metadata
  workflow-templates/npm-audit-fix.properties.json
  workflow-templates/npm-audit-fix.svg
Labels: 3. to review, bug

#150 Create README.md
  profile/README.md
Labels: 3. to review, discussion, documentation

#154 fix: ensure proper php modules to setup Nextcloud
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-oci.yml
  workflow-templates/phpunit-pgsql.yml
  workflow-templates/phpunit-sqlite.yml
  workflow-templates/update-nextcloud-ocp-matrix.yml
  workflow-templates/update-nextcloud-ocp.yml
Labels: 3. to review

#157 chore: Update a few workflows actions
  .github/workflows/command-rebase.yml
  .github/workflows/dispatch-workflow.yml
  .github/workflows/lint-yaml.yml
  workflow-templates/appstore-build-publish.yml
  workflow-templates/command-compile.yml
  workflow-templates/command-rebase.yml
  workflow-templates/lint-eslint.yml
  workflow-templates/lint-info-xml.yml
  workflow-templates/lint-php-cs.yml
  workflow-templates/lint-php.yml
  workflow-templates/lint-stylelint.yml
  workflow-templates/node.yml
  workflow-templates/npm-audit-fix.yml
  workflow-templates/npm-publish.yml
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-oci.yml
  workflow-templates/phpunit-pgsql.yml
  workflow-templates/phpunit-sqlite.yml
  workflow-templates/psalm-matrix.yml
  workflow-templates/psalm.yml
  workflow-templates/update-nextcloud-ocp-matrix.yml
  workflow-templates/update-nextcloud-ocp.yml
Labels: 3. to review

#158 Rerun block-merge-freeze.yml and ignore drafts
  workflow-templates/block-merge-freeze.yml
Labels: 3. to review, bug

#151 feat: add documentation workflow
  workflow-templates/documentation.properties.json
  workflow-templates/documentation.svg
  workflow-templates/documentation.yml
Labels: 3. to review

#160 chore: update workflows from templates
  .github/workflows/fixup.yml
Labels: 3. to review, dependencies, automated

#161 chore: drop stable24 and add stable27 to static analysis and ocp update
  workflow-templates/psalm-matrix.yml
  workflow-templates/update-nextcloud-ocp.yml
Labels: 3. to review

#153 allow dependency up downgrade for ocp peer dependencies
  workflow-templates/psalm-matrix.yml
Labels: 3. to review, bug

#168 fix(phpunit): Print nextcloud.log to help debugging
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-oci.yml
  workflow-templates/phpunit-pgsql.yml
  workflow-templates/phpunit-sqlite.yml
Labels: 3. to review
