Repository nextcloud/.github, pull requests merged in 2024-02, with the labels that each got.

#289 fix(command-compile): rebase before compiling and fetch origin
  workflow-templates/command-compile.properties.json
  workflow-templates/command-compile.yml
Labels: 3. to review

#296 chore: update workflows from templates
  .github/workflows/fixup.yml
Labels: 3. to review, dependencies, automated

#298 select a php version available on the runner for phpunit
  workflow-templates/phpunit-mariadb.yml
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-oci.yml
  workflow-templates/phpunit-pgsql.yml
  workflow-templates/phpunit-sqlite.yml
Labels: 3. to review

#316 fix(npmauditfix): Make commit semantic
  workflow-templates/npm-audit-fix.yml
Labels: 3. to review, bug
