Repository nextcloud/.github, pull requests merged in 2024-04, with the labels that each got.

#338 fix(workflow-templates): Adjust duplicate versions steps in OpenAPI workflow
  workflow-templates/openapi.yml
Labels: 3. to review, bug

#349 Add reuse GH action to organization-wide template repo
  workflow-templates/reuse.yml
Labels: 4. to release

#351 chore: Update workflows from templates + enable dependabot
  .github/dependabot.yml
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/command-rebase.yml
  .github/workflows/lint-yaml.yml
Labels: 3. to review

#347 enh(appstore-build-publish): without dev dependencies
  workflow-templates/appstore-build-publish.yml
Labels: 3. to review
