Repository nextcloud/.github, pull requests merged in 2024-09, with the labels that each got.

#423 Bump and properly pin approve action
  workflow-templates/renovate-approve-merge.yml
Labels: 4. to release

#431 chore: update buildjet/cache
  workflow-templates/command-compile.yml
  workflow-templates/cypress.yml
Labels: 3. to review

#328 don't install nextcloud/ocp for workflows that don't require it
  workflow-templates/lint-php-cs.yml
  workflow-templates/phpunit-mariadb.yml
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-oci.yml
  workflow-templates/phpunit-pgsql.yml
  workflow-templates/phpunit-sqlite.yml
  workflow-templates/psalm-matrix.yml
  workflow-templates/psalm.yml
Labels: 3. to review, enhancement

#435 validate app version from info.xml against the tag name in public action
  workflow-templates/appstore-build-publish.yml
Labels: 3. to review
