Repository nextcloud/.github, pull requests merged in 2024-07, with the labels that each got.

#397 Update reuse to v4 and migrate to toml definitions
  .github/workflows/reuse.yml
  .reuse/dep5
  REUSE.toml
  workflow-templates/reuse.yml
Labels: 4. to release

#402 fix(prfeedback): Bots are in the non-community list now
  workflow-templates/pr-feedback.yml
Labels: 3. to review

#404 Reformat to not make `npx prettier` check fail
  .github/workflows/reuse.yml
  workflow-templates/reuse.yml
Labels: 3. to review

#407 fix(compile): Fix compile command fork detection
  workflow-templates/command-compile.yml
Labels: 3. to review

#406 fix(appstore-build-publish): keep dev dependencies to build frontend
  workflow-templates/appstore-build-publish.yml
Labels: 3. to review, bug
