Repository nextcloud/.github, pull requests merged in 2025-04, with the labels that each got.

#524 fix(psalm): Run matrix psalm on the lowest applicable PHP version
  workflow-templates/psalm-matrix.yml
Labels: 3. to review

#525 fix: use more conventional commit message for workflow updates
  .github/workflows/dispatch-workflow.yml
Labels: 3. to review

#526 fix: Generate classmap-authoritative on release to improve performance
  workflow-templates/appstore-build-publish.yml
Labels: 3. to review

#532 fix: Nextcloud 29 is EOL
  workflow-templates/npm-audit-fix.yml
  workflow-templates/update-nextcloud-ocp-matrix.yml
  workflow-templates/update-nextcloud-ocp.yml
Labels: 3. to review, bug

#535 feat: add type checking workflow
  workflow-templates/lint-typescript.properties.json
  workflow-templates/lint-typescript.yml
Labels: 3. to review, enhancement

#538 fix: Do not update dependencies in vendor-bin when removing nextcloud/ocp
  workflow-templates/lint-php-cs.yml
  workflow-templates/phpunit-mariadb.yml
  workflow-templates/phpunit-mysql.yml
  workflow-templates/phpunit-oci.yml
  workflow-templates/phpunit-pgsql.yml
  workflow-templates/phpunit-sqlite.yml
  workflow-templates/psalm-matrix.yml
  workflow-templates/psalm.yml
Labels: 3. to review, bug
