Repository nextcloud/.github, pull requests merged in 2025-01, with the labels that each got.

#490 fix: Harden base_ref checks in block-merge actions
  workflow-templates/block-merge-eol.yml
  workflow-templates/block-merge-freeze.yml
Labels: bug

#493 fix: Update MariaDB versions to supported versions of Nextcloud 31
  workflow-templates/phpunit-mariadb.yml
Labels: 3. to review

#497 fix: Harden approve-merge checks
  .github/workflows/dispatch-workflow.yml
  .github/workflows/lint-yaml.yml
  .github/workflows/reuse.yml
  workflow-templates/appstore-build-publish.yml
  workflow-templates/command-compile.yml
  workflow-templates/command-openapi.yml
  workflow-templates/cypress.yml
  workflow-templates/dependabot-approve-merge.yml
  workflow-templates/documentation.yml
  workflow-templates/npm-audit-fix.yml
  workflow-templates/pr-feedback.yml
  workflow-templates/psalm-matrix.yml
  workflow-templates/psalm.yml
  workflow-templates/renovate-approve-merge.yml
  workflow-templates/reuse.yml
  workflow-templates/update-nextcloud-ocp-matrix.yml
  workflow-templates/update-nextcloud-ocp.yml
Labels: 3. to review

#495 fix(reuse): Restrict workflow to read permissions
  .github/workflows/dispatch-workflow.yml
  .github/workflows/lint-yaml.yml
  .github/workflows/reuse.yml
  workflow-templates/appstore-build-publish.yml
  workflow-templates/command-compile.yml
  workflow-templates/command-openapi.yml
  workflow-templates/cypress.yml
  workflow-templates/documentation.yml
  workflow-templates/npm-audit-fix.yml
  workflow-templates/pr-feedback.yml
  workflow-templates/psalm-matrix.yml
  workflow-templates/psalm.yml
  workflow-templates/reuse.yml
  workflow-templates/update-nextcloud-ocp-matrix.yml
  workflow-templates/update-nextcloud-ocp.yml
Labels: 3. to review, bug

#499 fix(phpunit-mariadb): Use correct script name and env variable
  workflow-templates/phpunit-mariadb.yml
Labels: 3. to review, bug
