Repository nextcloud/.github, pull requests merged in 2025-05, with the labels that each got.

#543 ci: run reuse check on ubuntu-latest-low
  workflow-templates/reuse.yml
Labels: 3. to review, github_actions

#542 feat(npm-publish): check that tag matches package.json version
  workflow-templates/npm-publish.yml
Labels: 3. to review, enhancement

#547 Bump fsfe/reuse-action to 5.0.2
  workflow-templates/reuse.yml
Labels: 4. to release
